- name:
  hosts: backend
  become: yes
  vars:
  tasks:
   - name:
     ansible.builtin.command: dnf module disable nodejs -y

   - name: enable nodejs20
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.package:
      name: nodejs
      state: present  

   - name: create expence user 
     ansible.builtin.user:    #ansible taken care irrespective of distribution user creation by using ansible module
      name: expence
   - name: creating the directory
     ansible.builtin.file:
      path: /app
      state: directory
   - name: download the code
     ansible.builtin.url:
      url:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /temp/backend.zip
   - name: 
     ansible.builtin.unarchive:
      src: /temp/backend
      dest: /app
      remote_src: yes   #Unarchive a file is  on the remote machine so we this command
