- name:
  hosts: backend
  become: yes
  vars:
   login_host: 172.31.25.129
   password_root: ExpenseApp@1
  tasks:
   - name:
     ansible.builtin.command: dnf module disable nodejs -y

   - name: enable nodejs20
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.package:
      name: nodejs
      state: present  

   - name: create expence user 
     ansible.builtin.user:    #ansible taken care irrespective of distribution user creation by using ansible module
      name: expence
   - name: creating the directory
     ansible.builtin.file:
      path: /app
      state: directory
   - name: download the backend code
     ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  #  - name: download the code
  #    ansible.builtin.get_url:
  #     url:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
  #     dest: /temp/backend.zip
  #     ignore_errors: false
   - name: 
     ansible.builtin.unarchive:
      src: /tmp/backend
      dest: /app
      remote_src: yes   #Unarchive a file is  on the remote machine so we this command
   - name: install dependencies
     ansible.builtin.command: npm install
     args:
      chdir: /app  #we should run this on wherw packgage,json file so this args chnage the dir and run that command
   - name: copy the backnedcose
     ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service
   - name: ansible to install pymysql
     ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9
   - name: import mysql
     community.mysql.mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      target: /app/schema/backend.sql
      name: all
      state: import
   - name: daemon reload
     ansible.builtin.systemd_service:
      daemon_reload: true
      state: restarted
      name: backend
